# Generated by Django 4.1.2 on 2023-02-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Property',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('property_name', models.CharField(max_length=20)),
                ('property_location', models.CharField(max_length=20)),
                ('property_image', models.ImageField(upload_to='')),
                ('property_feature', models.CharField(max_length=300)),
                ('property_tag', models.TextField()),
            ],
        ),
    ]
