# Generated by Django 4.1.6 on 2023-02-14 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0004_property_property_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='property',
            name='property_items',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
