# Generated by Django 4.1.6 on 2023-02-15 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0005_property_property_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Banner_image', models.ImageField(upload_to='')),
                ('Banner_title', models.CharField(max_length=30)),
                ('Banner_tagline', models.TextField()),
            ],
        ),
    ]
