# Generated by Django 4.1.6 on 2023-02-15 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0006_banner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='banner',
            name='Banner_tagline',
        ),
        migrations.RemoveField(
            model_name='banner',
            name='Banner_title',
        ),
    ]
