# Generated by Django 4.1.6 on 2023-02-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0007_remove_banner_banner_tagline_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Testimonial_image', models.ImageField(upload_to='')),
                ('Testimonial_name', models.CharField(max_length=100)),
                ('Testimonial_profession', models.CharField(max_length=30)),
                ('Testimonial_sentence', models.TextField()),
            ],
        ),
    ]
