# Generated by Django 4.1.6 on 2023-02-15 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0008_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blog_date', models.CharField(max_length=10)),
                ('blog_profilepic', models.ImageField(upload_to='')),
                ('blog_profilename', models.CharField(max_length=50)),
                ('blog_image', models.ImageField(upload_to='')),
                ('blog_title', models.CharField(max_length=100)),
                ('blog_sentence', models.TextField()),
            ],
        ),
    ]
