# Generated by Django 4.1.6 on 2023-03-02 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0011_remove_blog_blog_date_remove_blog_blog_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='professionals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('professionals_name', models.CharField(max_length=50)),
                ('professionals_image', models.ImageField(upload_to='')),
                ('professionals_post', models.CharField(max_length=50)),
            ],
        ),
    ]
