# Generated by Django 4.1.6 on 2023-03-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0015_contact'),
    ]

    operations = [
        migrations.CreateModel(
            name='workingwithshelterlet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workingwithshelterlet_id', models.CharField(max_length=30)),
                ('workingwithshelterlet_title', models.CharField(max_length=50)),
                ('workingwithshelterlet_sentence', models.TextField()),
            ],
        ),
    ]
