# Generated by Django 4.1.6 on 2023-03-03 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0017_rename_workingwithshelterlet_services_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='brandspartners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brandspartners_image', models.ImageField(upload_to='')),
            ],
        ),
    ]
