# Generated by Django 4.1.6 on 2023-03-04 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0018_brandspartners'),
    ]

    operations = [
        migrations.CreateModel(
            name='Popularplaces',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Popularplaces_image', models.ImageField(upload_to='')),
                ('Popularplaces_title', models.CharField(max_length=40)),
                ('Popularplaces_details', models.CharField(max_length=100)),
            ],
        ),
    ]
