# Generated by Django 4.1.6 on 2023-03-11 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0019_popularplaces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='phone',
            field=models.CharField(max_length=50),
        ),
    ]
